### PR TITLE
Upgrade runtime dependencies

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Stemcell is failing to install on Ruby 2.2 (due to the older version of the `json` gem) - this upgrades the runtime dependences to resolve that issue.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Looks like this breaks 1.9.3 support - not sure if you guys are using >= 2.0, so I could leave this alone or could change the chef dependency to `~> 11.0` to bring back 1.9.3.

**Comment by jacobwgillespie** [comment]
Okay, I think I found a solution with conditional dependencies - also see http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ for a note about not including the Gemfile.lock in a Rubygem.

**Comment by igor47** [comment]
this is great! thanks for the PR! i'm going to merge and then push an updated version to rubygems.

**Comment by jacobwgillespie** [comment]
Thanks! :+1:

**Pull request merged**
